AUOSMS/AUOSMS.MOBILE.NETCOREIMPORT/ViewModels/DirectPaymentViewModel.cs
using System;
using Iamport.RestApi.Models;

namespace AUOSMS.MOBILE.NETCOREIMPORT.ViewModels
{
    public class DirectPaymentViewModel
    {
        internal static DirectPaymentViewModel Create(Models.Payment payment, Models.Checkout checkout)
        {
            return new DirectPaymentViewModel
            {
                Name = checkout.Name,
                Amount = checkout.Amount,
                State = payment.State,
            };
        }

        public string Name { get; private set; }
        public decimal Amount { get; private set; }
        public Models.PaymentState State { get; private set; }
    }
}

AUOSMS/AUOSMS.MOBILE.NETCOREIMPORT/Controllers/CheckoutController.cs
using System;

using AUOSMS.MOBILE.NETCOREIMPORT.Repositories;
using AUOSMS.MOBILE.NETCOREIMPORT.ViewModels;

using Iamport.RestApi;

using Microsoft.AspNetCore.Mvc;

namespace AUOSMS.MOBILE.NETCOREIMPORT.Controllers
{
    /// <summary>
    /// 구매 정보 관련 컨트롤러
    /// </summary>
    [Route("[Controller]")]
    public class CheckoutController : Controller
    {
        private readonly CheckoutRepository checkoutRepository;
        private readonly IamportHttpClientOptions clientOptions;
        public CheckoutController(
            CheckoutRepository checkoutRepository,
            IamportHttpClientOptions clientOptions)
        {
            this.checkoutRepository = checkoutRepository ?? throw new ArgumentNullException(nameof(checkoutRepository));
            this.clientOptions = clientOptions ?? throw new ArgumentNullException(nameof(clientOptions));
        }

        /// <summary>
        /// 결제 요청(Checkout; 혹은 구매) 페이지
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Index()
        {
            return View(new RegisterCheckoutModel());
        }

        /// <summary>
        /// 구매 정보를 등록하고 결제 페이지로 이동합니다.
        /// </summary>
        /// <param name="model">구매 정보</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(RegisterCheckoutModel model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            // 새 구매 정보 저장
            var checkout = model.ToCheckout();
            checkoutRepository.Add(checkout);

            // 결제 페이지로 이동
            return RedirectToAction(nameof(Gateway), new { id = checkout.Id });
        }

        /// <summary>
        /// 해당 구매 정보를 결제하는 결제 게이트웨이 페이지.
        /// </summary>
        /// <param name="id">구매 정보 Id</param>
        /// <returns></returns>
        [HttpGet("{id}/gateway")]
        public IActionResult Gateway(Guid id)
        {
            var checkout = checkoutRepository.GetById(id);
            if (checkout == null)
            {
                return NotFound();
            }

            var viewModel = RequestPaymentViewModel.Create(
                checkout: checkout,
                iamportId: clientOptions.IamportId,
                paymentUrl: Url.Action(nameof(PaymentController.CreateAjax), "Payment"));
            return View(viewModel);
        }

        [HttpGet("{id}/PageNotFound")]
        public IActionResult PageNotFound(Guid id)
        {
            ViewData["Id"] = id;
            return View();
        }
    }
}

AUOSMS/AUOSMS.MOBILE.NETCOREIMPORT/Controllers/DirectPaymentController.cs
using System;
using System.Threading.Tasks;
using AUOSMS.MOBILE.NETCOREIMPORT.Repositories;
using AUOSMS.MOBILE.NETCOREIMPORT.ViewModels;

using Iamport.RestApi;
using Iamport.RestApi.Apis;
using Iamport.RestApi.Models;
using Microsoft.AspNetCore.Mvc;

namespace AUOSMS.MOBILE.NETCOREIMPORT.Controllers
{
    [Route("[Controller]")]
    public class DirectPaymentController : Controller
    {
        private readonly IPaymentsApi paymentsApi;
        private readonly ISubscribeApi subscribeApi;
        private readonly CheckoutRepository checkoutRepository;
        private readonly PaymentRepository paymentRepository;
        private readonly string iamportId;
        public DirectPaymentController(
            IPaymentsApi paymentsApi,
            ISubscribeApi subscribeApi,
            CheckoutRepository checkoutRepository,
            PaymentRepository paymentRepository,
            IamportHttpClientOptions clientOptions)
        {
            this.paymentsApi = paymentsApi ?? throw new ArgumentNullException(nameof(paymentsApi));
            this.subscribeApi = subscribeApi ?? throw new ArgumentNullException(nameof(subscribeApi));
            this.checkoutRepository = checkoutRepository ?? throw new ArgumentNullException(nameof(checkoutRepository));
            this.paymentRepository = paymentRepository ?? throw new ArgumentNullException(nameof(paymentRepository));
            if (clientOptions == null)
            {
                throw new ArgumentNullException(nameof(clientOptions));
            }
            iamportId = clientOptions.IamportId;
        }

        /// <summary>
        /// 비인증 결제 페이지
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Index()
        {
            return View(new RequestDirectPaymentModel());
        }

        /// <summary>
        /// 비인증 결제 요청
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(RequestDirectPaymentModel input)
        {
            if (ModelState.IsValid == false)
            {
                return View(nameof(Index), input);
            }

            // 비인증 구매는 구매 요청을 즉시 처리 가능.
            var checkout = Models.Checkout.Create(
                name: input.Name,
                amount: input.Amount,
                paymentGateway: input.PaymentGateway,
                isDigital: false,
                useEscrow: false,
                paymentMethod: PaymentMethod.CreditCard,
                customerName: input.CustomerName,
                customerEmail: input.CustomerEmail,
                customerPhoneNumber: input.CustomerPhoneNumber,
                returnUrl: null,
                virtualBankExpirationTime: DateTimeOffset.UtcNow);
            checkoutRepository.Add(checkout);

            var payment = Models.Payment.Create(checkout.Id);

            var request = new DirectPaymentRequest
            {
                CustomerId = null,  // 등록된 사용자 빌링키 없이 한번 진행
                TransactionId = payment.TransactionId,
                Vat = input.Vat,
                Amount = input.Amount,
                Title = input.Name,
                CardNumber = input.CardNumber,
                AuthenticationNumber = input.AuthenticationNumber,
                Expiry = input.Expiry,
                PartialPassword = input.PartialPassword,
                InstallmentMonths = 0,
                BuyerName = input.CustomerName,
                Email = input.CustomerEmail,
                PhoneNumber = input.CustomerPhoneNumber,
                Address = input.CustomerAddress,
                PostCode = input.CustomerPostCode,
            };

            Payment iamportPayment = null;
            try
            {
                iamportPayment = await subscribeApi.DoDirectPaymentAsync(request);
            }
            catch (IamportResponseException ex)
            {
                ModelState.AddModelError("iamport", ex.Message);
                return View(nameof(Index), input);
            }

            paymentRepository.Add(payment);
            RefreshPayment(iamportPayment, payment);

            return RedirectToAction(nameof(Result), new { transactionId = payment.TransactionId });
        }

        /// <summary>
        /// 구매 결과 페이지
        /// </summary>
        /// <param name="transactionId">거래 고유 ID</param>
        /// <returns></returns>
        [HttpGet("{transactionId}")]
        public IActionResult Result(string transactionId)
        {
            var payment = paymentRepository.GetByTransactionId(transactionId);
            if (payment == null)
            {
                return PageNotFound(transactionId);
            }
            var checkout = checkoutRepository.GetById(payment.CheckoutId);
            if (checkout == null)
            {
                return PageNotFound(transactionId);
            }

            var viewModel = PaymentViewModel.Create(payment, checkout);
            return View(viewModel);
        }

        /// <summary>
        /// 지정한 거래 ID의 결제가 발견되지 않았습니다.
        /// </summary>
        /// <param name="transactionId">거래 ID</param>
        /// <returns></returns>
        [HttpGet("{transactionId}/pagenotfound")]
        public IActionResult PageNotFound(string transactionId)
        {
            ViewData["TransactionId"] = transactionId;
            return View(nameof(PageNotFound));
        }

        // TODO:
        // 이 로직은 비지니스 로직을 담고 있습니다.
        // 비즈니스 레이어로 옮기는 것이 좋습니다.

        private void RefreshPayment(Payment iamportPayment, Models.Payment payment)
        {
            // 기존 상태(payment.State)와 최신 상태(iamportPayment.Status)를 비교합니다.
            switch (iamportPayment.Status)
            {
                case PaymentStatus.Ready:
                    if (iamportPayment.Method == PaymentMethod.VirtualBank
                        && !string.IsNullOrEmpty(iamportPayment.VirtualBankAccount))
                    {
                        payment.SetAwatingForVirtualBank(
                            iamportPayment.IamportId,
                            iamportPayment.PaymentGatewayTransactionId,
                            iamportPayment.VirtualBankName,
                            iamportPayment.VirtualBankAccount,
                            iamportPayment.VirtualBankAccountHolder);
                    }
                    else
                    {
                        payment.SetInProgress(iamportPayment.IamportId);
                    }
                    break;
                case PaymentStatus.Paid:
                    switch (iamportPayment.Method)
                    {
                        case PaymentMethod.CreditCard:
                            payment.SetPaidForCreditCard(
                                iamportPayment.IamportId,
                                iamportPayment.PaidAtUtc,
                                iamportPayment.PaymentGatewayTransactionId,
                                iamportPayment.ApplyNumber,
                                iamportPayment.CreditCardCompanyName,
                                iamportPayment.InstallmentPlanPeriod);
                            break;
                        case PaymentMethod.VirtualBank:
                            payment.SetPaiedForVirtualBank(
                                iamportPayment.IamportId,
                                iamportPayment.PaidAtUtc,
                                iamportPayment.PaymentGatewayTransactionId,
                                iamportPayment.VirtualBankName,
                                iamportPayment.VirtualBankAccount,
                                iamportPayment.VirtualBankAccountHolder);
                            break;
                        case PaymentMethod.Transfer:
                        case PaymentMethod.Mobile:
                        case PaymentMethod.CultureLand:
                        case PaymentMethod.SmartCulture:
                        case PaymentMethod.HappyMoney:
                        default:
                            payment.SetPaidForOthers(
                                iamportPayment.IamportId,
                                iamportPayment.PaidAtUtc,
                                iamportPayment.PaymentGatewayTransactionId);
                            break;
                    }
                    break;
                case PaymentStatus.Cancelled:
                    payment.SetCancelled(
                        iamportPayment.IamportId,
                        iamportPayment.CancelledAtUtc,
                        iamportPayment.CancelledReason,
                        iamportPayment.CancelledAmount);
                    break;
                case PaymentStatus.Failed:
                    payment.SetFailed(
                        iamportPayment.IamportId,
                        iamportPayment.FailedAtUtc,
                        iamportPayment.FailedReason);
                    break;
                default:
                    break;
            }
            paymentRepository.Update(payment);
        }
    }
}

AUOSMS/AUOSMS.MOBILE.NETCOREIMPORT/Views/DirectPayment/Index.cshtml
@model AUOSMS.MOBILE.NETCOREIMPORT.ViewModels.RequestDirectPaymentModel
@using Iamport.RestApi.Models
@{
    ViewData["Title"] = "비인증 결제 데모: 구매하기";
}
<div class="row">
    <h1>@ViewData["Title"]</h1>

    <div>
        <p>이 샘플 애플리케이션은 고객에게 카드 번호 및 기타 정보를 입력받아 공인인증서 없이 직접 RestAPI로 결제하는 프로세스를 모사합니다.</p>
        <p>지원하는 결제사는 KG이니시스, 나이스정보통신, JTnet 입니다.</p>
        <p>이 샘플 애플리케이션에서 이루어지는 모든 내용은 애플리케이션의 로컬 메모리에만 유지되므로 애플리케이션이 호스팅된 서버를 종료하면 진행했던 모든 상태가 유실됩니다.</p>
    </div>
    <hr />
    <form id="directpayment" class="form-horizontal" asp-antiforgery="true" asp-controller="DirectPayment" asp-action="Index">
        <div asp-validation-summary="All" class="form-group text-danger">
        </div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label">구매 상품 이름</label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Amount" class="col-md-2 control-label">금액</label>
            <div class="col-md-10">
                <input asp-for="Amount" class="form-control" type="number" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Vat" class="col-md-2 control-label">VAT(optional)</label>
            <div class="col-md-10">
                <input asp-for="Vat" class="form-control" type="number" />
                <span asp-validation-for="Vat" class="text-danger"></span>
            </div>
        </div>
        <hr/>
        <div class="form-group">
            <label asp-for="PaymentGateway" class="col-md-2 control-label">결제 게이트웨이사</label>
            <div class="col-md-10">
                <select asp-for="PaymentGateway" asp-items="@Html.GetSelectListFromStaticMembers<PaymentGateway>()" class="form-control"></select>
                <span asp-validation-for="PaymentGateway" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="CardNumber" class="col-md-2 control-label">카드번호(dddd-dddd-dddd-dddd)</label>
            <div class="col-md-10">
                <input asp-for="CardNumber" class="form-control" />
                <span asp-validation-for="CardNumber" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Expiry" class="col-md-2 control-label">유효기간(YYYY-MM)</label>
            <div class="col-md-10">
                <input asp-for="Expiry" class="form-control" />
                <span asp-validation-for="Expiry" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="AuthenticationNumber" class="col-md-2 control-label">주민번호 앞 6자리(법인카드는 법인번호 10자리)</label>
            <div class="col-md-10">
                <input asp-for="AuthenticationNumber" class="form-control" />
                <span asp-validation-for="AuthenticationNumber" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PartialPassword" class="col-md-2 control-label">패스워드 앞 2자리(법인카드는 공백)</label>
            <div class="col-md-10">
                <input asp-for="PartialPassword" class="form-control" />
                <span asp-validation-for="PartialPassword" class="text-danger"></span>
            </div>
        </div>
        <hr />
        <div class="form-group">
            <label asp-for="CustomerName" class="col-md-2 control-label">(optional)구매자 이름</label>
            <div class="col-md-10">
                <input asp-for="CustomerName" class="form-control" />
                <span asp-validation-for="CustomerName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="CustomerPhoneNumber" class="col-md-2 control-label">(optional)구매자 전화번호</label>
            <div class="col-md-10">
                <input asp-for="CustomerPhoneNumber" class="form-control" />
                <span asp-validation-for="CustomerPhoneNumber" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="CustomerEmail" class="col-md-2 control-label">(optional)구매자 이메일</label>
            <div class="col-md-10">
                <input asp-for="CustomerEmail" class="form-control" />
                <span asp-validation-for="CustomerEmail" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="CustomerAddress" class="col-md-2 control-label">(optional)구매자 주소</label>
            <div class="col-md-10">
                <input asp-for="CustomerAddress" class="form-control" />
                <span asp-validation-for="CustomerAddress" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="CustomerPostCode" class="col-md-2 control-label">(optional)구매자 우편번호</label>
            <div class="col-md-10">
                <input asp-for="CustomerPostCode" class="form-control" />
                <span asp-validation-for="CustomerPostCode" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-2">
                <button type="submit" class="btn btn-primary form-control">구매하기</button>
            </div>
        </div>
    </form>
</div>

AUOSMS/AUOSMS.MOBILE.NETCOREIMPORT/Views/DirectPayment/PageNotFound.cshtml
@using AUOSMS.MOBILE.NETCOREIMPORT.Models
@{
    ViewData["Title"] = "비인증-결제 데모: 해당 결제 ID 존재하지 않음";
}
<div class="row">
    <h1>@ViewData["Title"]</h1>

    <h3>거래 ID @ViewData["TransactionId"] 은 존재하지 않습니다.</h3>

    @Html.ActionLink("비인증-결제 데모", "Index", "Checkout")
</div>

AUOSMS/AUOSMS.MOBILE.NETCOREIMPORT/Views/DirectPayment/Result.cshtml
@model AUOSMS.MOBILE.NETCOREIMPORT.ViewModels.PaymentViewModel
@using AUOSMS.MOBILE.NETCOREIMPORT.Models
@{
    ViewData["Title"] = "비인증-결제 데모: 결제 진행상태";
}
<div class="row">
    <h1>@ViewData["Title"]</h1>

    <div>
        <p>이 페이지는 현재 결제 결과를 표시합니다.</p>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">결제 내용</div>
        <div class="panel-body">
            <ul>
                <li>상품: @Model.Name</li>
                <li>금액: @Model.Amount.ToString("#,##0.##") 원</li>
                <li>진행 상태: @Html.DisplayFor(model => model.State)</li>
            </ul>
            <a id="refresh" class="btn btn-primary">결과 새로고침</a>
            <a href="@Url.Action("Index", "DirectPayment")" class="btn btn-default">처음부터 다시하기</a>
        </div>
    </div>
</div>

@section scripts {
    <script type="text/javascript">
    (function () {
        $('#refresh').click(function () {
            location.reload();
        });
    })();
    </script>
}